name: Create Issue For Prebuild Errors

on:
  workflow_run:
    workflows: [Codespaces Prebuilds, Codespaces Prebuilds (ppe)]
    types:
    - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    # TODO!
    #if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PPE_RUNS_URL: https://github.com/${{ github.repository }}/actions/workflows/codespaces/create_codespaces_prebuilds_ppe?query=branch%3Amain
      PROD_RUNS_URL: https://github.com/${{ github.repository }}/actions/workflows/codespaces/create_codespaces_prebuilds?query=branch%3Amain
      IS_PPE: ${{ endsWith(github.event.workflow.name, '(ppe)') }}
    steps:
      - name: Alert on failure
        run: |
          if [[ "$IS_PPE" = "true" ]]; then
            url="$PPE_RUNS_URL"
            env="PPE"
          else 
            url="$PROD_RUNS_URL"
            env="Prod"
          fi
          
          title="⛑ ${{ github.repository }} $env Prebuild failed"
          
          body=$(echo -e "The prebuild creation workflow has failed for $env.\n
          Check the action's [run history]($url) to investigate any recent errors.")
          
          # Specify the repo so that we can avoid cloning
          gh issue create -t "$title" -b "$body" -R "${{ github.repository }}"
