name: Create Issue For Prebuild Errors

on:
  workflow_run:
    workflows: [Codespaces Prebuilds, Codespaces Prebuilds (ppe)]
    types:
    - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    # TODO!
    #if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PPE_RUNS_URL: https://github.com/${{ github.repository }}/actions/workflows/codespaces/create_codespaces_prebuilds_ppe?query=branch%3Amain
      PRODUCTION_RUNS_URL: https://github.com/${{ github.repository }}/actions/workflows/codespaces/create_codespaces_prebuilds?query=branch%3Amain
      IS_PPE: ${{ endsWith(github.event.workflow.name, '(ppe)') }}
    steps:
      - name: Alert on failure
        run: |
          [[ "$IS_PPE" = "true" ]] && url="$PPE_RUNS_URL" || url="$PRODUCTION_RUNS_URL"
          
          title="⛑ ${{ github.repository }} Prebuild failed"
          
          body="The prebuild creation workflow has failed\n\n \
          Check [run history]($url) to investigate recent error"
          
          # Specify the repo so that we can avoid cloning
          gh issue create -t "$title" -b "$body" -R "${{ github.repository }}"
