name: Create Issue For Prebuild Errors

on:
  workflow_run:
    workflows: [Codespaces Prebuilds, Codespaces Prebuilds (ppe)]
    types:
    - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    # TODO!
    #if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Alert on failure
        run: |
          title="⛑ ${{ github.repository }} Prebuild failed"
          
          body="The prebuild creation workflow has failed \n\n \
          Check [run history](${{ github.event.workflow.url }}) to investigate recent errors"
          
          gh issue create -t "$title" -b "$body"
