name: Create Issue For Prebuild Errors

on:
  workflow_run:
    workflows: [Codespaces Prebuilds, Codespaces Prebuilds (ppe)]
    types:
    - completed
jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJSON('["success", "failure", "cancelled"]'), github.event.workflow_run.conclusion) }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PPE_RUNS_URL: https://github.com/${{ github.repository }}/actions/workflows/codespaces/create_codespaces_prebuilds_ppe?query=branch%3Amain
      PROD_RUNS_URL: https://github.com/${{ github.repository }}/actions/workflows/codespaces/create_codespaces_prebuilds?query=branch%3Amain
      IS_PPE: ${{ endsWith(github.event.workflow.name, '(ppe)') }}
      IS_SUCCESS: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Handle Prebuild Completion
        run: |
          if [[ "$IS_PPE" = "true" ]]; then
            url="$PPE_RUNS_URL"
            env="PPE"
          else 
            url="$PROD_RUNS_URL"
            env="Prod"
          fi
                
          title="⛑ ${{ github.repository }} $env Prebuild failed"
          
          existing_number=$(gh issue list \
            --search "$title" \
            --app github-actions \
            -R "${{ github.repository }}" \
            --limit 1 \
            --json number \
            | jq -r '.[0].number')

          if [[ "$IS_SUCCESS" = "true" ]]; then
            if [[ "$existing_number" = "null" ]]; then
              # Success and no existing issue, nothing to do
            else
              body="Closing as the prebuild has succeeded in [this run](${{ github.event.workflow_run.html_url }})"
              
              gh issue comment $existing_number -b "$body" -R "${{ github.repository }}"
              gh issue close $existing_number -R "${{ github.repository }}"
            fi
          else # failed
            if [[ "$existing_number" = "null" ]]; then
              body=$(echo -e "The prebuild creation workflow has failed for $env.\n
              Check the action's [run history]($url) to investigate any recent errors.")
            
              gh issue create -t "$title" -b "$body" -R "${{ github.repository }}"
            else
              body="Ping! Looks like this is still happening in [this run](${{ github.event.workflow_run.html_url }}) :sweat_smile:"
              
              gh issue comment $existing_number -b "$body" -R "${{ github.repository }}"
            fi
          fi

