name: Test action

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
  
    - uses: Amadevus/pwsh-script@fbb60107f8d707858c4ab46336d3963b7991782e
      name: Run script
      with:
        script: |
          Write-ActionInfo ($github.event | ConvertTo-Json -depth 100)
          Write-ActionInfo ($github.event.pull_request.merged | ConvertTo-Json -depth 100)
